### PR TITLE
transalte

### PR DESCRIPTION
**Pull request by gzuhlwang**
translate

### CODE REVIEW

**Comment by qbig** [comment]
@miguelmota We are done :)

**Comment by qbig** [comment]
@gzuhlwang left `event-read-0xprotocol` to you 👍

**Comment by gzuhlwang** [comment]
@qbig yeah, I'm workin on it.

**Comment by gzuhlwang** [comment]
@qbig all done！

**Comment by miguelmota** [comment]
@qbig @gzuhlwang you guys rock 👍

**Pull request merged**
